[[mvc-cors]]
= CORS
[.small]#{docSpringWebFlux}#webflux-cors[WebFlux]#

Spring MVC使你可以处理CORS（跨域资源共享）。本节介绍如何执行此操作。


[[mvc-cors-intro]]
== 介绍
[.small]#{docSpringWebFlux}#webflux-cors-intro[WebFlux]#

出于安全原因，浏览器禁止AJAX调用当前来源以外的资源。
例如，你可以将你的银行帐户放在一个浏览器标签中，将 `evil.com` 放在另一个浏览器标签中。
来自 `evil.com` 的脚本不能使用你的凭据向你的银行API发送AJAX请求 -- 例如：从你的帐户中提取资金！

跨域资源共享（CORS）是 http://caniuse.com/#feat=cors[大多数浏览器]实施的
http://www.w3.org/TR/cors/[W3C规范]，可让你指定授权哪种类型的跨域请求，
而不是使用基于IFRAME或JSONP的安全性较低且功能较弱的变通办法。


[[mvc-cors-processing]]
== 处理过程
[.small]#{docSpringWebFlux}#webflux-cors-processing[WebFlux]#

CORS规范分为预检，简单和实际请求。要了解CORS的工作原理，你可以阅读
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS[本文]以及其他内容，或者参阅规范以获取更多详细信息。

Spring MVC `HandlerMapping` 实现为CORS提供内置支持。成功将请求映射到处理程序后，
`HandlerMapping` 实现将检查给定请求和处理程序的CORS配置，并采取进一步的措施。
预检请求直接处理，而简单和实际的CORS请求被拦截、验证，并设置了必需的CORS响应头。

为了启用跨域请求（即存在 `Origin` 请求头，并且与请求的主机不同），你需要具有一些显式声明的CORS配置。
如果找不到匹配的CORS配置，则预检请求将被拒绝。没有将CORS响应头添加到简单和实际CORS请求的响应中，
因此，浏览器拒绝了它们。

可以使用基于URL模式的 `CorsConfiguration` 映射分别
{javadocSpring}/web/servlet/handler/AbstractHandlerMapping.html#setCorsConfigurations-java.util.Map-[配置]
每个 `HandlerMapping`。在大多数情况下，应用程序使用MVC
Java配置或XML名称空间声明此类映射，这导致将单个全局映射传递给所有 `HandlerMapping` 实例。

You can combine global CORS configuration at the `HandlerMapping` level with more
fine-grained, handler-level CORS configuration. For example, annotated controllers can use
class- or method-level `@CrossOrigin` annotations (other handlers can implement
`CorsConfigurationSource`).

你可以将 `HandlerMapping` 级别的全局CORS配置与更细粒度的处理程序级别的CORS配置结合使用。
例如，带注解的控制器可以使用类或方法级别的 `@CrossOrigin` 注解（其他处理程序可以实现 `CorsConfigurationSource`）。

全局和本地配置组合的规则通常是相加的 -- 例如：所有全局和所有本地源。
对于那些只能接受单个值的属性（例如 `allowCredentials` 和 `maxAge`），本地值将覆盖全局值。
有关更多详细信息，请参见 {javadocSpring}/web/cors/CorsConfiguration.html#combine-org.springframework.web.cors.CorsConfiguration-[`CorsConfiguration#combine(CorsConfiguration)`]。

[TIP]
====
要从源中了解更多信息或进行高级自定义，请查看后面的代码：

* `CorsConfiguration`
* `CorsProcessor`, `DefaultCorsProcessor`
* `AbstractHandlerMapping`
====


[[mvc-cors-controller]]
== `@CrossOrigin`
[.small]#{docSpringWebFlux}#webflux-cors-controller[WebFlux]#

{javadocSpring}/web/bind/annotation/CrossOrigin.html[`@CrossOrigin`]
注解启用被注解的控制器方法上的跨域请求，如以下示例所示：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
@RestController
@RequestMapping("/account")
public class AccountController {

    @CrossOrigin
    @GetMapping("/{id}")
    public Account retrieve(@PathVariable Long id) {
        // ...
    }

    @DeleteMapping("/{id}")
    public void remove(@PathVariable Long id) {
        // ...
    }
}
----

默认情况下，`@CrossOrigin` 允许：

* 所有源。
* 所有请求头。
* 控制器方法映射到的所有HTTP方法。

默认情况下，`allowedCredentials` 未启用，因为它建立了一个信任级别，可以公开敏感的用户特定信息
（例如：cookie和CSRF令牌），并且仅在适当的地方使用。

`maxAge` 设置为30分钟。

`@CrossOrigin` 在类级别上也受支持，并且被所有方法继承，如以下示例所示：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
@CrossOrigin(origins = "http://domain2.com", maxAge = 3600)
@RestController
@RequestMapping("/account")
public class AccountController {

    @GetMapping("/{id}")
    public Account retrieve(@PathVariable Long id) {
        // ...
    }

    @DeleteMapping("/{id}")
    public void remove(@PathVariable Long id) {
        // ...
    }
}
----

你可以在类级别和方法级别上使用 `@CrossOrigin`，如以下示例所示：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
@CrossOrigin(maxAge = 3600)
@RestController
@RequestMapping("/account")
public class AccountController {

    @CrossOrigin("http://domain2.com")
    @GetMapping("/{id}")
    public Account retrieve(@PathVariable Long id) {
        // ...
    }

    @DeleteMapping("/{id}")
    public void remove(@PathVariable Long id) {
        // ...
    }
}
----


[[mvc-cors-global]]
== 全局配置
[.small]#{docSpringWebFlux}#webflux-cors-global[WebFlux]#

除了细粒度的控制器方法级别配置外，你可能还想定义一些全局CORS配置。
你可以在任何 `HandlerMapping` 上分别设置基于URL的 `CorsConfiguration` 映射。
但是，大多数应用程序都使用MVC Java配置或MVC XML名称空间来执行此操作。

默认情况下，全局配置启用以下功能：

* 所有源。
* 所有请求头。
* `GET`, `HEAD` 和 `POST` 方法.

默认情况下，`allowedCredentials` 未启用，因为它建立了一个信任级别，可以公开敏感的用户特定信息
（例如：cookie和CSRF令牌），并且仅在适当的地方使用。

`maxAge` 设置为30分钟。


[[mvc-cors-global-java]]
=== Java配置
[.small]#{docSpringWebFlux}#webflux-cors-global[WebFlux]#

要在MVC Java配置中启用CORS，可以使用 `CorsRegistry` 回调，如以下示例所示：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
@Configuration
@EnableWebMvc
public class WebConfig implements WebMvcConfigurer {

    @Override
    public void addCorsMappings(CorsRegistry registry) {

        registry.addMapping("/api/**")
            .allowedOrigins("http://domain2.com")
            .allowedMethods("PUT", "DELETE")
            .allowedHeaders("header1", "header2", "header3")
            .exposedHeaders("header1", "header2")
            .allowCredentials(true).maxAge(3600);

        // Add more mappings...
    }
}
----


[[mvc-cors-global-xml]]
=== XML配置

要在XML名称空间中启用CORS，可以使用 `<mvc:cors>` 元素，如以下示例所示：

[source,xml,indent=0]
[subs="verbatim"]
----
<mvc:cors>

    <mvc:mapping path="/api/**"
        allowed-origins="http://domain1.com, http://domain2.com"
        allowed-methods="GET, PUT"
        allowed-headers="header1, header2, header3"
        exposed-headers="header1, header2" allow-credentials="true"
        max-age="123" />

    <mvc:mapping path="/resources/**"
        allowed-origins="http://domain1.com" />

</mvc:cors>
----


[[mvc-cors-filter]]
== CORS过滤器
[.small]#{docSpringWebFlux}#webflux-cors-webfilter[WebFlux]#

你可以通过内置的 {javadocSpring}/web/filter/CorsFilter.html[`CorsFilter`]应用CORS支持。

NOTE: 如果你尝试将 `CorsFilter` 与Spring Security一起使用，请记住Spring Security内置了对CORS的
https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#cors[支持]。

要配置过滤器，请将 `CorsConfigurationSource` 传递给它的构造函数，如以下示例所示：

[source,java,indent=0]
[subs="verbatim"]
----
CorsConfiguration config = new CorsConfiguration();

// Possibly...
// config.applyPermitDefaultValues()

config.setAllowCredentials(true);
config.addAllowedOrigin("http://domain1.com");
config.addAllowedHeader("*");
config.addAllowedMethod("*");

UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
source.registerCorsConfiguration("/**", config);

CorsFilter filter = new CorsFilter(source);
----
