[[mvc-view]]
= 视图技术
[.small]#{docSpringWebFlux}#webflux-view[WebFlux]#

Spring MVC中视图技术的使用是可插入的，无论你决定使用Thymeleaf，Groovy标记模板，JSPs还是其他技术，主要取决于配置更改。
本章介绍与Spring MVC集成的视图技术。我们假设你已经熟悉<<mvc-viewresolver>>。


[[mvc-view-thymeleaf]]
== Thymeleaf
[.small]#{docSpringWebFlux}#webflux-view-thymeleaf[WebFlux]#

Thymeleaf是一种现代的服务器端Java模板引擎，它强调可以通过双击在浏览器中预览的自然HTML模板，
这对于独立处理UI模板(例如：由设计人员完成)而不需要运行服务器是非常有用的。如果要替换为JSP，
Thymeleaf提供了最广泛的功能集之一，以使这种过渡更加容易。Thymeleaf是积极开发和维护的。
有关更完整的介绍，请参见 http://www.thymeleaf.org/[Thymeleaf]项目主页。

Thymeleaf与Spring MVC的集成由Thymeleaf项目管理。该配置涉及一些Bean声明，例如：
`ServletContextTemplateResolver`，`SpringTemplateEngine` 和 `ThymeleafViewResolver`。
有关更多详细信息，请参见 http://www.thymeleaf.org/documentation.html[Thymeleaf+Spring]。


[[mvc-view-freemarker]]
== FreeMarker
[.small]#{docSpringWebFlux}#webflux-view-freemarker[WebFlux]#

http://www.freemarker.org[Apache FreeMarker] 是一个模板引擎，用于生成从HTML到电子邮件等的任何类型的文本输出。
Spring框架具有内置的集成，可以将Spring MVC与FreeMarker模板一起使用。


[[mvc-view-freemarker-contextconfig]]
=== 视图配置
[.small]#{docSpringWebFlux}#webflux-view-freemarker-contextconfig[WebFlux]#

以下示例显示如何配置使用FreeMarker视图技术：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
    @Configuration
    @EnableWebMvc
    public class WebConfig implements WebMvcConfigurer {

        @Override
        public void configureViewResolvers(ViewResolverRegistry registry) {
            registry.freemarker();
        }

        // Configure FreeMarker...

        @Bean
        public FreeMarkerConfigurer freeMarkerConfigurer() {
            FreeMarkerConfigurer configurer = new FreeMarkerConfigurer();
            configurer.setTemplateLoaderPath("/WEB-INF/freemarker");
            return configurer;
        }
    }
----

以下示例显示了如何在XML中进行配置：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
    <mvc:annotation-driven/>

    <mvc:view-resolvers>
        <mvc:freemarker/>
    </mvc:view-resolvers>

    <!-- Configure FreeMarker... -->
    <mvc:freemarker-configurer>
        <mvc:template-loader-path location="/WEB-INF/freemarker"/>
    </mvc:freemarker-configurer>
----

另外，你也可以声明 `FreeMarkerConfigurer` bean，以完全控制所有属性，如以下示例所示：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
    <bean id="freemarkerConfig" class="org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer">
        <property name="templateLoaderPath" value="/WEB-INF/freemarker/"/>
    </bean>
----

你的模板需要存储在上例 `FreeMarkerConfigurer` 所示的指定的目录中。给定上述配置，如果你的控制器返回 `welcome` 视图名称，
则解析器将查找 `/WEB-INF/freemarker/welcome.ftl` 模板。


[[mvc-views-freemarker]]
=== FreeMarker配置
[.small]#{docSpringWebFlux}#webflux-views-freemarker[WebFlux]#

你可以通过在 `FreeMarkerConfigurer` bean上设置适当的bean属性，将FreeMarker的'Settings' 和 'SharedVariables'
直接传递给FreeMarker配置对象（由Spring管理）。`freemarkerSettings` 属性需要一个 `java.util.Properties` 对象，
而 `freemarkerVariables` 属性需要一个 `java.util.Map`。以下示例显示了如何使用 `FreeMarkerConfigurer`：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
    <bean id="freemarkerConfig" class="org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer">
        <property name="templateLoaderPath" value="/WEB-INF/freemarker/"/>
        <property name="freemarkerVariables">
            <map>
                <entry key="xml_escape" value-ref="fmXmlEscape"/>
            </map>
        </property>
    </bean>

    <bean id="fmXmlEscape" class="freemarker.template.utility.XmlEscape"/>
----

有关应用于 `Configuration` 对象的设置和变量的详细信息，请参阅FreeMarker文档。

[[mvc-view-freemarker-forms]]
=== 表单处理

Spring提供了一个供JSP使用的标签库，其中包含一个 `<spring:bind/>` 元素。
该元素主要允许表单显示来自表单支持对象的值，并显示来自Web或业务层中 `Validator` 的验证失败的结果。
Spring还支持FreeMarker中的相同功能，并为生成表单输入元素本身提供了额外的方便宏。

[[mvc-view-document]]
== PDF和Excel

Spring提供了返回HTML以外的输出的方法，包括PDF和Excel电子表格。本节介绍如何使用这些功能。


[[mvc-view-document-intro]]
=== 文档视图简介

HTML页面并非始终是用户查看模型输出的最佳方法，而Spring使从模型数据动态生成PDF文档或Excel电子表格变得简单。
该文档是视图，并从服务器以正确的内容类型进行流传输，以（希望）使客户端PC能够运行其电子表格或PDF查看器应用程序作为响应。

为了使用Excel视图，你需要将Apache POI库添加到你的类路径中。为了生成PDF，你需要添加（最好是）OpenPDF库。

NOTE: 如果可能，你应该使用基础文档生成库的最新版本。特别是，我们强烈建议你使用OpenPDF（例如：OpenPDF 1.2.12）
而不是过时的原始iText 2.1.7，因为OpenPDF会得到积极维护并修复了不可信任PDF内容的重要漏洞。


[[mvc-view-document-pdf]]
=== PDF视图

单词列表的简单PDF视图可以继承 `org.springframework.web.servlet.view.document.AbstractPdfView`
并实现 `buildPdfDocument()` 方法，如以下示例所示：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
    public class PdfWordList extends AbstractPdfView {

        protected void buildPdfDocument(Map<String, Object> model, Document doc, PdfWriter writer,
                HttpServletRequest request, HttpServletResponse response) throws Exception {

            List<String> words = (List<String>) model.get("wordList");
            for (String word : words) {
                doc.add(new Paragraph(word));
            }
        }
    }
----

控制器可以从外部视图定义（按名称引用）返回此视图，也可以从处理程序方法返回为 `View` 实例。


[[mvc-view-document-excel]]
=== Excel视图

从Spring Framework 4.2开始，提供 `org.springframework.web.servlet.view.document.AbstractXlsView`
作为Excel视图的基类。它基于Apache POI，具有取代过时的 `AbstractExcelView` 类的专用子类
（`AbstractXlsxView` 和 `AbstractXlsxStreamingView`）。

编程模型类似于 `AbstractPdfView`，其中 `buildExcelDocument()` 作为中央模板方法，
控制器能够从外部定义（按名称）或从处理程序方法作为 `View` 实例返回这种视图。


[[mvc-view-jackson]]
== Jackson
[.small]#{docSpringWebFlux}#webflux-view-httpmessagewriter[WebFlux]#

Spring提供了对Jackson JSON库的支持。


[[mvc-view-json-mapping]]
=== 基于Jackson的JSON MVC视图
[.small]#{docSpringWebFlux}#webflux-view-httpmessagewriter[WebFlux]#

`MappingJackson2JsonView` 使用Jackson类库的 `ObjectMapper` 将响应内容呈现为JSON。
默认情况下，模型映射的全部内容（特定于框架的类除外）均编码为JSON。对于需要过滤映射内容的情况，
可以使用 `modelKeys` 属性指定要编码的一组特定的模型属性。你也可以使用 `extractValueFromSingleKeyModel` 属性，
以将单键模型中的值直接提取并序列化，而不是作为模型属性的映射。

你可以根据需要使用Jackson提供的注解来自定义JSON映射。当需要进一步控制时，
可以在需要为特定类型提供自定义JSON序列化器和反序列化器的情况下，通过 `ObjectMapper` 属性注入自定义 `ObjectMapper`。

[[mvc-view-xml-mapping]]
=== 基于Jackson的XML视图
[.small]#{docSpringWebFlux}#webflux-view-httpmessagewriter[WebFlux]#

`MappingJackson2XmlView` 使用 https://github.com/FasterXML/jackson-dataformat-xml[Jackson XML扩展程序]
的 `XmlMapper` 将响应内容呈现为XML。如果模型包含多个条目，则应使用 `modelKey` bean属性显式设置要序列化的对象。
如果模型包含单个条目，则会自动序列化。

你可以根据需要使用JAXB或Jackson提供的注解自定义XML映射。当需要进一步控制时，
可以在需要为特定类型提供自定义XML序列化器和反序列化器的情况下，通过 `ObjectMapper` 属性注入自定义 `XmlMapper`。
